config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :tasks
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :tasks
  validates :name, :presence => true


    def completed
      completed_tasks =[]
      self.tasks.each() do |task|
        if task.complete
          completed_tasks.push(task)
        end
      end
      return completed_tasks
    end


    def not_completed
      incomplete_tasks =[]
      self.tasks.each() do |task|
        if !task.complete
          incomplete_tasks.push(task)
        end
      end
      return incomplete_tasks
    end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list

  validates :description, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    render :index
  end

  def show
    @list = List.find(params[:id])
    render :show
  end

  def new
    @list = List.new
    render :new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
    render :edit
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to list_path(@list)
    else
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end



  private
  def list_params
    params.require(:list).permit(:name)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @task = @list.tasks.new
  end

  def create
    @list = List.find(params[:list_id])
    @task = @list.tasks.new(task_params)
    # binding.pry
    if @task.save
      redirect_to list_path(@task.list)
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:list_id])
    @task = @list.tasks.find(params[:id])
    render :edit
  end

  def update
    # binding.pry
    @list = List.find(params[:list_id])
    @task = @list.tasks.find(params[:id])
    if params[:mark] == "true"
      @task.update(:complete => true)
      redirect_to list_path(@list)
    elsif params[:mark] == "false"
      @task.update(:complete => false)
      redirect_to list_path(@list)
    elsif @task.update(task_params)
      redirect_to list_path(@list)
    else
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:list_id])
    @task = @list.tasks.find(params[:id])
    @task.destroy
    redirect_to list_path(@list)
  end

  private
    def task_params
      params.require(:task).permit(:description, :complete)

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet"      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<body>
<nav>
  <h1><%= link_to "To Do", lists_path%></h1>
  <h2><%= link_to "create", new_list_path %></h2>
</nav>
<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= render "layouts/errors", :object => @list %>

<%= form_for @list do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/lists/edit.html.erb
<h1>Edit list</h1>

<%= render "form" %>

app/views/lists/index.html.erb
<h1>Lists</h1>
<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list) %></li>
  <% end %>
</ul>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render "form" %>

app/views/lists/show.html.erb
<h1><%=@list.name %></h1>

<%= link_to "Edit List", edit_list_path(@list)%>



<% if @list.tasks.any? %>
  <h4>Here are the task for this list:</h4>
  <h5>Completed Tasks</h5>
  <ul>
    <% @list.completed.each do |task| %>
      <li>

        <%= task.description %> |
        <%= link_to "Edit Task", edit_list_task_path(@list, task) %> |
        <%= link_to "mark as incomplete", list_task_path(@list, task, :mark => false), :method => :patch %> |
        <%= link_to "Delete Task", list_task_path(@list, task),
                          :data => {:confirm => "Are you sure?",
                                :method => "delete"} %>
      </li>

      </li>
    <% end %>
  </ul>

  <h5>Incomplete Tasks</h5>
  <ul>
    <% @list.not_completed.each do |task| %>
      <li>

        <%= task.description %> |
        <%= link_to "Edit Task", edit_list_task_path(@list, task) %> |
        <%= link_to "mark as complete", list_task_path(@list, task, :mark => true), :method => :patch %> |
        <%= link_to "Delete Task", list_task_path(@list, task),
                          :data => {:confirm => "Are you sure?",
                                :method => "delete"} %>
      </li>
        </li>
    <% end %>
  </ul>


  <% else %>
  <p>There are no tasks yet!</p>
<% end %>

  <p><%= link_to "Add a task", new_list_task_path(@list) %></p>
  <p><%= link_to "Delete List", list_path(@list),
                       :data => {:confirm => "Are you sure?",
                                      :method => "delete"} %></p>

  <p><%= link_to "Return to lists", lists_path %></p>

app/views/tasks/_form.html.erb
<%= render('layouts/errors', :object => @task) %>

<%= form_for [@list, @task] do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%=f.hidden_field :complete, :value => false %>
  <p><%= f.submit %></p>
<% end %>

app/views/tasks/edit.html.erb
<h2><%=@task.description%></h2>


<%= form_for [@list, @task] do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :complete %>
  <%=f.check_box(:complete, :value => true) %>
  <p><%= f.submit %></p>
<% end %>

app/views/tasks/new.html.erb
<h1>New task for <%= @list.name %></h1>

<%= render 'form' %>